services:
  postgres:
    image: 'postgis/postgis:${POSTGRES_V}'
    environment:
      - 'POSTGRES_DB=${POSTGRES_NAME}'
      - 'POSTGRES_PASSWORD=${POSTGRES_PASS}'
      - 'POSTGRES_USER=${POSTGRES_USER}'
      - 'TZ=${ZONE}'
    ports:
      - '${POSTGRES_PORT}:5432'