spring:
  config:
    import:
      - optional:file:.env[.properties]
  application:
    name: sigdosi
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_NAME:sigdosi}
    password: ${POSTGRES_PASS}
    username: ${POSTGRES_USER:postgres}
  jpa:
    open-in-view: false
  servlet:
    multipart:
      max-file-size: 5MB
  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    password: ${MAIL_PASS}
    username: ${MAIL_USER}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  cloud:
    aws:
      region:
        static: ${AWS_REGION}
      credentials:
        access-key: ${AWS_ACCESS_KEY}
        secret-key: ${AWS_SECRET_KEY}
      s3:
        enabled: ${AWS_S3_ENABLE:false}

server:
  port: ${SERVER_PORT:8000}
  servlet:
    context-path: /api

springdoc:
  api-docs:
    enabled: ${DOCS_ENABLE:false}
  swagger-ui:
    enabled: ${DOCS_ENABLE:false}

app:
  zone: ${ZONE:America/Guatemala}
  client:
    origin: ${CLIENT_ORIGIN}
  cookies:
    same-site: ${COOKIES_SITE:strict}
    path: ${COOKIES_PATH:/}
  files:
    storage:
      type: ${STORAGE_TYPE:local}
      local:
        path: ${STORAGE_LOCAL_PATH}

iam:
  security:
    jwt:
      public-key: file:${JWT_PUBLIC_KEY}
      private-key: file:${JWT_PRIVATE_KEY}
  auth:
    flow-token:
      time-to-live: ${FLOW_TTL:5m}
      cleanup: ${FLOW_CLEANUP:0 */10 * * * *}
    password-token:
      time-to-live: ${PASS_TTL:10m}
      cleanup: ${PASS_CLEANUP:0 */20 * * * *}
    refresh-token:
      time-to-live: ${REFRESH_TTL:7d}
      cleanup: ${REFRESH_CLEANUP:0 */30 * * * *}
    access-token:
      time-to-live: ${ACCESS_TTL:15m}