# Fragments
template.mail.footer=Este es un mensaje automático, no respondas a este correo.

# Auth - Set password
template.mail.auth.set-password.greeting=Hola <strong>{0}</strong>:
template.mail.auth.set-password.link-expires-at=Este enlace dejará de ser válido el <strong>{0}</strong>.
template.mail.auth.set-password.ignore-request=Si no realizaste esta solicitud, puedes ignorar este correo.
template.mail.auth.set-password.setup.subject=Establecimiento de contraseña
template.mail.auth.set-password.reset.subject=Restablecimiento de contraseña
template.mail.auth.set-password.setup.body-text=Se ha recibido una solicitud para establecer la primera contraseña de tu cuenta. Utiliza el siguiente enlace para continuar con el proceso.
template.mail.auth.set-password.reset.body-text=Se ha recibido una solicitud para restablecer la contraseña de tu cuenta. Utiliza el siguiente enlace para continuar con el proceso.
template.mail.auth.set-password.setup.button-text=Establecer
template.mail.auth.set-password.reset.button-text=Restablecer