# Fragments
template.mail.footer=Este es un mensaje automático, no respondas a este correo.

# Auth - Set password
template.mail.auth.password-setup.greeting=Hola <strong>{0}</strong>:
template.mail.auth.password-setup.link-expires-at=Este enlace dejará de ser válido el <strong>{0}</strong>.
template.mail.auth.password-setup.ignore-request=Si no realizaste esta solicitud, puedes ignorar este correo.
template.mail.auth.password-setup.set.subject=Establecimiento de contraseña
template.mail.auth.password-setup.reset.subject=Restablecimiento de contraseña
template.mail.auth.password-setup.set.body-text=Se ha recibido una solicitud para establecer la primera contraseña de tu cuenta. Utiliza el siguiente enlace para continuar con el proceso.
template.mail.auth.password-setup.reset.body-text=Se ha recibido una solicitud para restablecer la contraseña de tu cuenta. Utiliza el siguiente enlace para continuar con el proceso.
template.mail.auth.password-setup.set.button-text=Establecer
template.mail.auth.password-setup.reset.button-text=Restablecer