
--
-- CREATE TABLE plan_type
-- (
--     id          UUID        NOT NULL,
--     code        VARCHAR(10) NOT NULL UNIQUE,
--     name        VARCHAR(35) NOT NULL,
--     description TEXT,
--     created_at  TIMESTAMPTZ NOT NULL,
--     updated_at  TIMESTAMPTZ NOT NULL,
--     PRIMARY KEY (id)
-- );
--
--
--
-- CREATE TABLE property_element
-- (
--     id                   UUID        NOT NULL,
--     property_id          UUID        NOT NULL,
--     building_element_id  UUID        NOT NULL,
--     building_material_id UUID,
--     created_at           TIMESTAMPTZ NOT NULL,
--     updated_at           TIMESTAMPTZ NOT NULL,
--     PRIMARY KEY (id),
--     CONSTRAINT FK_property_TO_property_component
--         FOREIGN KEY (property_id) REFERENCES property (id),
--     CONSTRAINT FK_building_element_TO_property_component
--         FOREIGN KEY (building_element_id) REFERENCES building_element (id),
--     CONSTRAINT FK_building_material_TO_property_component
--         FOREIGN KEY (building_material_id) REFERENCES building_material (id),
--     CONSTRAINT UQ_property_building_element
--         UNIQUE (property_id, building_element_id)
-- );
--
-- CREATE TABLE property_image
-- (
--     id          UUID        NOT NULL,
--     property_id UUID        NOT NULL,
--     filename    VARCHAR(45) NOT NULL UNIQUE,
--     created_at  TIMESTAMPTZ NOT NULL,
--     updated_at  TIMESTAMPTZ NOT NULL,
--     PRIMARY KEY (id),
--     CONSTRAINT FK_property_TO_property_image
--         FOREIGN KEY (property_id) REFERENCES property (id)
-- );
--
-- CREATE TABLE property_plan
-- (
--     id           UUID        NOT NULL,
--     plan_type_id UUID        NOT NULL,
--     property_id  UUID        NOT NULL,
--     filename     VARCHAR(45) NOT NULL UNIQUE,
--     version      SMALLINT,
--     created_at   TIMESTAMPTZ NOT NULL,
--     updated_at   TIMESTAMPTZ NOT NULL,
--     PRIMARY KEY (id),
--     CONSTRAINT FK_plan_type_TO_property_plan
--         FOREIGN KEY (plan_type_id) REFERENCES plan_type (id),
--     CONSTRAINT FK_property_TO_property_plan
--         FOREIGN KEY (property_id) REFERENCES property (id),
--     CONSTRAINT UQ_plan_type_property_version
--         UNIQUE (plan_type_id, property_id, version)
-- );